name: Check code quality
on:
  push:
jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Install git-crypt
        run: sudo apt-get install -y git-crypt
      - name: Unlock secrets
        run: |
          echo ${{ secrets.GIT_CRYPT_KEY }} | base64 --decode >> key
          git-crypt unlock ./key
      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
      - name: Setup project
        run: flutter pub get
      - name: Format code
        run: flutter format -l 120 --set-exit-if-changed .
  analyze-code:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Install git-crypt
        run: sudo apt-get install -y git-crypt
      - name: Unlock secrets
        run: |
          echo ${{ secrets.GIT_CRYPT_KEY }} | base64 --decode >> key
          git-crypt unlock ./key
      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
      - name: Setup project
        run: flutter pub get
      - name: Analyze code
        run: flutter analyze
